base_eprint_data = {'screen': 'Search',
                    'dataset': 'archive',
                    'documents_merge': 'ALL',
                    'title_merge': 'ALL',
                    'creators_name_merge': 'ALL',
                    'abstract_merge': 'ALL',
                    'keywords_merge': 'ALL',
                    'subjects_merge': 'ANY',
                    'type': 'software',
                    'divisions_merge': 'ANY',
                    'rpa_merge': 'ANY',
                    'editors_name_merge': 'ALL',
                    'refereed': 'EITHER',
                    'publication_merge': 'ALL',
                    'thesis_advisors_name_merge': 'ALL',
                    'satisfyall': 'ALL',
                    'order': '-date/creators_name/title',
                    '_action_search': 'Search'}

ntu_data = {'screen': 'Search',
            'dataset': 'archive',
            'documents_merge': 'ALL',
            'title_merge': 'ALL',
            'creators_name_merge': 'ALL',
            'creators_id_merge': 'ALL',
            'ntu_abstract_merge': 'ALL',
            'keywords_merge': 'ALL',
            'ntu_item_type': 'Software',
            'divisions_merge': 'ANY',
            'department_merge': 'ALL',
            'editors_name_merge': 'ALL',
            'editors_id_merge': 'ALL',
            'ntu_ispublished_merge': 'ALL',
            'refereed': 'EITHER',
            'publication_merge': 'ALL',
            'ntu_emda_subject_merge': 'ALL',
            'satisfyall': 'ALL',
            'order': '-date/creators_name/title',
            '_action_search': 'Search'}

reading_data = {'screen': 'Search',
                'dataset': 'archive',
                '_action_search': 'Search',
                'documents_merge': 'ALL',
                'title_merge': 'ALL',
                'alt_title_merge': 'ALL',
                'data_type': 'Software',
                'creators_name_merge': 'ALL',
                'contributors_name_merge': 'ALL',
                'creators_research_division_merge': 'ALL',
                'copyright_holders_merge': 'ALL',
                'publisher_merge': 'ALL',
                'id_number_merge': 'ALL',
                'corp_creators_name_merge': 'ALL',
                'divisions_merge': 'ANY',
                'legal_ethical_merge': 'ALL',
                'keywords_merge': 'ALL',
                'projects_name_merge': 'ALL',
                'funders_funders_merge': 'ALL',
                'pub_in_progress': 'EITHER',
                'repo_link_link_merge': 'ALL',
                'satisfyall': 'ALL',
                'order': '-date/creators_name/title'}

default_pure_data = {
    'format': '',
    'type': '/dk/atira/pure/researchoutput/researchoutputtypes/nontextual/software',
    'nofollow': 'true'
}
